name: Development workflow

run-name: "${{ github.actor}} perfom ${{ github.event_name}} on ${{ github.head_ref || github.ref_name  }}"

on:
    push:
        branches: 
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm install
    
    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test -- -u
